prefix = "./resource"
dataset = "news"
corpus = "line.toml"
index = "idx"

[[analyzers]]
method = "ngram-word"
ngram = 1
	[[analyzers.filter]]
    type = "icu-tokenizer"
    suppress-tags = "true"

	
